#!/bin/sh

if git diff --cached --name-only | grep -E '^spell/en_SW\.(dic|aff)$' >/dev/null &&
    ! git diff --cached --name-only | grep -E '^spell/en\..*\.spl$' >/dev/null
then
    echo 'Spell files changed but compiled *.spl not staged' >&2
    exit 1
fi
